export const metadata = {
  title: 'Login | AI Customer Support',
  description: 'Generated by Next.js',
}
import '../globals.css'

export default function LoginLayout({ children }) {
  return <section>{children}</section>
}
