export const metadata = {
  title: 'AI Customer Support',
  description: 'Generated by Next.js',
}
import './globals.css'
import { Toaster } from 'react-hot-toast'
export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body><Toaster position='top-center'/>{children}</body>
    </html>
  )
}
