
export const metadata = {
  title: 'AI Customer Support',
  description: 'Generated by Next.js',
}
import './globals.css'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='relative'>
        <div className="absolute w-full bg-gray-50 min-h-screen flex items-center justify-center px-16 z-[1]">
          <div className="relative w-full max-w-lg">
            <div className="absolute top-0 -left-4 w-72 h-72 bg-purple-300 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob"></div>
            <div className="absolute top-0 -right-4 w-72 h-72 bg-yellow-300 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-2000"></div>
            <div className="absolute -bottom-8 left-20 w-72 h-72 bg-pink-300 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-4000"></div>
          </div>
        </div>
        <div className="absolute float-left clear-left z-[2] w-full min-h-screen h-full bg-none">{children}</div>
      </body>
    </html>
  )
}
