export const metadata = {
  title: 'Sign Up | AI Customer Support',
  description: 'Generated by Next.js',
}
import '../globals.css'

export default function SingupLayout({ children }) {
  return <section>{children}</section>
}