
export const metadata = {
  title: 'Sign Up | AI Customer Support',
  description: 'Generated by Next.js',
}
import '../globals.css'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
